"""Testing module."""
__all__ = ("gui_test_wrapper",
           "test_clang_complete_file",
           "test_clang_utils",
           "test_cmake_file",
           "test_makefile",
           "test_compilation_db",
           "test_CppProperties",
           "test_c_cpp_properties",
           "test_complete",
           "test_flag",
           "test_flags_source",
           "test_macro_parser",
           "test_error_vis",
           "test_settings",
           "test_style",
           "test_tools",
           "test_unique_list",
           "test_view_config")
